// AUTO-GENERATED type stub for offline typechecking. Not the real client.
declare module '@prisma/client' {
  export type Department = 'COORDINATOR' | 'FACTORY_MANAGER' | 'PRODUCTION_MANAGER' | 'CUTTING_MARKER' | 'WAREHOUSE' | 'EXTERNAL_OPS' | 'PACKING' | 'QUALITY' | 'FOLLOW_UP' | 'FINANCE' | 'ADMIN';
  export type RefKind = 'SEASON' | 'FABRIC' | 'FIT' | 'BLOCK_PATTERN' | 'ITEM_TYPE' | 'GENDER' | 'SHIPPING_METHOD' | 'EXTERNAL_WORK_SORT' | 'EXTERNAL_WORK_TYPE' | 'POSITION' | 'UNIT' | 'ITEM_SORT' | 'THREAD_COLOR' | 'REFERENCE' | 'COLLAR' | 'CUFF' | 'SIZE_LABEL' | 'FABRIC_COMPOSITION' | 'BRAND_LOGO';
  export type Priority = 'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT';
  export type OrderStatus = 'DRAFT' | 'WAITING_APPROVAL' | 'READY_FOR_PRODUCTION' | 'IN_PRODUCTION' | 'PRODUCTION_DELAYED' | 'QUALITY_CHECK' | 'QUALITY_BLOCKED' | 'PACKING' | 'READY_TO_SHIP' | 'SHIPPED' | 'COMPLETED' | 'CANCELLED';
  export type QtyLedger = 'ORDER' | 'STOCK' | 'CUT' | 'IN_LINE' | 'OUT_LINE' | 'PACKED' | 'SHIPPED' | 'SECOND_DEGREE';
  export type NoteKind = 'GENERAL' | 'SPREAD' | 'CUT' | 'PACKING' | 'EXTERNAL';
  export type StageKey = 'CUSTOMER_ORDER_REF' | 'ORDER_DETAILS' | 'MAIN_ORDER' | 'PROFORMA_INVOICE' | 'PROGRESS_STATUS' | 'CUT_ORDER' | 'LAYING_FABRIC' | 'BILL_OF_MATERIAL' | 'CUSTOM_INSTRUCTIONS' | 'EXTERNAL_ORDER' | 'STOCK' | 'FOLLOW_UP' | 'PRODUCTION_FOLLOW_UP' | 'PACKING' | 'AUDIT' | 'ACTUAL_COSTING' | 'DATABASE' | 'INVOICE' | 'COMPLETED';
  export type StageStatus = 'NOT_STARTED' | 'IN_PROGRESS' | 'WAITING' | 'COMPLETED' | 'BLOCKED' | 'OVERDUE' | 'NOT_REQUIRED';
  export type TaskStatus = 'NOT_STARTED' | 'IN_PROGRESS' | 'WAITING' | 'COMPLETED' | 'BLOCKED';
  export type BomCategory = 'FABRIC' | 'THREAD' | 'LABEL' | 'TRANSFER' | 'BADGE' | 'LOGO' | 'SPONSOR' | 'SIZE' | 'POLY_BAG' | 'BUTTER_PAPER' | 'STICKY_TAPE' | 'BARCODE_PAPER' | 'HALF_BOX' | 'CARTON' | 'TAPE' | 'ACCESSORY' | 'OTHER';
  export type MaterialType = 'FABRIC' | 'THREAD' | 'TRIM' | 'LABEL' | 'BUTTON' | 'ZIPPER' | 'ELASTIC' | 'PRINT_TRANSFER' | 'BADGE' | 'PACKAGING' | 'CARTON' | 'POLY_BAG' | 'ACCESSORY' | 'CHEMICAL' | 'OTHER';
  export type MovementType = 'RECEIPT' | 'ISSUE' | 'RETURN' | 'ADJUSTMENT' | 'WASTAGE' | 'TRANSFER_IN' | 'TRANSFER_OUT';
  export type ReservationStatus = 'ACTIVE' | 'FULFILLED' | 'RELEASED' | 'CANCELLED';
  export type UnitOfMeasure = 'M' | 'CM' | 'YD' | 'KG' | 'G' | 'PCS' | 'DZN' | 'ROLL' | 'CONE' | 'SET' | 'BOX' | 'L';
  export type ExternalOpStatus = 'NOT_SENT' | 'WAITING_APPROVAL' | 'SENT' | 'IN_PROGRESS' | 'RETURNED' | 'CANCELLED';
  export type ApprovalType = 'PRINT_ARTWORK' | 'EMBROIDERY' | 'COLOR' | 'SAMPLE' | 'LABEL' | 'PACKING' | 'PRODUCTION';
  export type ApprovalStatus = 'PENDING' | 'APPROVED' | 'REJECTED' | 'CHANGES_REQUESTED';
  export type ProductionOperation = 'CUTTING' | 'SEWING' | 'PRINTING' | 'EMBROIDERY' | 'WASHING' | 'FINISHING' | 'PACKING';
  export type AuditType = 'FINAL_AUDIT' | 'BEFORE_IRON' | 'BEFORE_PACKING' | 'IN_PACKING' | 'INLINE';
  export type AuditResult = 'PENDING' | 'PASS' | 'FAIL';
  export type DefectCategory = 'COLOR_COMBINATION' | 'FABRIC_DEFECT' | 'CONSTRUCTION_STITCHING' | 'TRIMMING' | 'PRINT_EMBROIDERY' | 'CLEANLINESS' | 'PACKING' | 'MEASUREMENTS';
  export type ShipmentStatus = 'NOT_READY' | 'READY' | 'BOOKED' | 'SHIPPED' | 'DELIVERED';
  export type CostGroup = 'FABRIC' | 'ACCESSORY' | 'EXTERNAL' | 'LABOUR' | 'OTHER';
  export type DocumentType = 'CUSTOMER_PO' | 'CUSTOMER_REFERENCE' | 'ARTWORK' | 'TECH_PACK' | 'FABRIC_PHOTO' | 'SAMPLE_PHOTO' | 'MARKER_FILE' | 'BOM' | 'EXTERNAL_OP_DOC' | 'PACKING_LIST' | 'QUALITY_REPORT' | 'INVOICE' | 'SHIPPING_DOC' | 'PROFORMA_INVOICE' | 'OTHER';
  export type NotificationPriority = 'LOW' | 'NORMAL' | 'HIGH' | 'URGENT';
  export type ChangeCategory = 'ORDER' | 'PRODUCTION' | 'INVENTORY' | 'MATERIALS' | 'TASKS' | 'QUALITY' | 'SHIPMENT' | 'APPROVALS' | 'DOCUMENTS' | 'ADMIN';
  export type EmailStatus = 'PENDING' | 'SENT' | 'FAILED';
  export type NotificationType = 'TASK_ASSIGNED' | 'TASK_OVERDUE' | 'APPROVAL_REQUESTED' | 'APPROVAL_RECEIVED' | 'MATERIAL_SHORTAGE' | 'PRODUCTION_DELAY' | 'QUALITY_FAILURE' | 'PACKING_COMPLETED' | 'SHIPMENT_READY' | 'ORDER_OVERDUE' | 'MENTIONED';
  export type ImportStatus = 'UPLOADED' | 'DETECTED' | 'MAPPED' | 'VALIDATED' | 'COMMITTED' | 'FAILED';

  export interface Role {
    id: string;
    key: string;
    label: string;
    description: string | null;
    permissions: string[];
    isSystem: boolean;
    users: User[];
    createdAt: Date;
    updatedAt: Date;
    _count: any;
  }
  export interface User {
    id: string;
    email: string;
    name: string;
    passwordHash: string;
    department: Department;
    phone: string | null;
    active: boolean;
    lastLoginAt: Date | null;
    isSuperAdmin: boolean;
    disabledAt: Date | null;
    disabledReason: string | null;
    disabledById: string | null;
    disabledBy: User | null;
    disabledUsers: User[];
    createdById: string | null;
    createdBy: User | null;
    createdUsers: User[];
    mustChangePassword: boolean;
    passwordChangedAt: Date | null;
    failedLoginCount: number;
    lockedUntil: Date | null;
    roleId: string;
    role: Role;
    coordinatedOrders: Order[];
    externalManagedOrders: Order[];
    assignedTasks: Task[];
    completedTasks: Task[];
    taskComments: TaskComment[];
    activityLogs: ActivityLog[];
    auditTrails: AuditTrail[];
    notifications: Notification[];
    attachments: Attachment[];
    savedColumnMappings: SavedColumnMapping[];
    productionRecords: ProductionRecord[];
    materialIssuesGiven: MaterialIssue[];
    materialIssuesTaken: MaterialIssue[];
    materialMovements: MaterialMovement[];
    materialReservations: MaterialReservation[];
    qualityAudits: QualityAudit[];
    approvalsRequested: Approval[];
    importJobs: ImportJob[];
    completedStages: OrderStage[];
    changeEvents: ChangeEvent[];
    proformaInvoices: ProformaInvoice[];
    createdAt: Date;
    updatedAt: Date;
    _count: any;
  }
  export interface Client {
    id: string;
    name: string;
    code: string | null;
    contactName: string | null;
    email: string | null;
    phone: string | null;
    shippingAddress: string | null;
    billingAddress: string | null;
    notes: string | null;
    active: boolean;
    orders: Order[];
    columnMappings: SavedColumnMapping[];
    createdAt: Date;
    updatedAt: Date;
    _count: any;
  }
  export interface Factory {
    id: string;
    name: string;
    code: string | null;
    address: string | null;
    contact: string | null;
    phone: string | null;
    isExternal: boolean;
    active: boolean;
    orders: Order[];
    externalOrders: Order[];
    externalOperations: ExternalOperation[];
    qualityAudits: QualityAudit[];
    createdAt: Date;
    updatedAt: Date;
    _count: any;
  }
  export interface RefColor {
    id: string;
    name: string;
    hex: string | null;
    position: number;
    active: boolean;
    orderColors: OrderColor[];
    bomItems: BomItem[];
    _count: any;
  }
  export interface RefSize {
    id: string;
    name: string;
    longName: string | null;
    position: number;
    active: boolean;
    orderSizes: OrderSize[];
    _count: any;
  }
  export interface RefValue {
    id: string;
    kind: RefKind;
    value: string;
    valueAr: string | null;
    position: number;
    active: boolean;
    _count: any;
  }
  export interface Order {
    id: string;
    poNumber: string;
    orderName: string;
    season: string;
    itemType: string | null;
    gender: string | null;
    styleNumber: string | null;
    fit: string | null;
    blockPattern: string | null;
    fabric: string | null;
    fabric2: string | null;
    fabric3: string | null;
    fabricDescription: string | null;
    shippingMethod: string | null;
    pricePerPieceUsd: Prisma.Decimal | null;
    cutPercentage: Prisma.Decimal;
    accessoryPercentage: Prisma.Decimal;
    poDate: Date | null;
    promisedShippingDate: Date | null;
    requiredDeliveryDate: Date | null;
    fabricDeliveryToSupplier: Date | null;
    supplierDeliveryDate: Date | null;
    externalReference: string | null;
    externalWorkSort: string | null;
    externalWorkType: string | null;
    shippingAddress: string | null;
    billingAddress: string | null;
    priority: Priority;
    cancelled: boolean;
    cancelledReason: string | null;
    cachedProgressPct: number | null;
    cachedStatus: OrderStatus | null;
    cachedStageKey: StageKey | null;
    clientId: string;
    client: Client;
    factoryId: string | null;
    factory: Factory | null;
    externalFactoryId: string | null;
    externalFactory: Factory | null;
    coordinatorId: string | null;
    coordinator: User | null;
    outsideWorkManagerId: string | null;
    outsideWorkManager: User | null;
    colors: OrderColor[];
    sizes: OrderSize[];
    quantities: StageQuantity[];
    notes: OrderNote[];
    stages: OrderStage[];
    tasks: Task[];
    bomItems: BomItem[];
    materialIssues: MaterialIssue[];
    materialMovements: MaterialMovement[];
    materialReservations: MaterialReservation[];
    cuttingRecords: CuttingRecord[];
    markers: Marker[];
    fabricRecords: FabricRecord[];
    externalOperations: ExternalOperation[];
    approvals: Approval[];
    customInstructions: CustomInstruction[];
    proformaInvoices: ProformaInvoice[];
    productionRecords: ProductionRecord[];
    qualityAudits: QualityAudit[];
    packingLists: PackingList[];
    shipments: Shipment[];
    costing: CostingRecord | null;
    attachments: Attachment[];
    activityLogs: ActivityLog[];
    auditTrails: AuditTrail[];
    notifications: Notification[];
    changeEvents: ChangeEvent[];
    createdAt: Date;
    updatedAt: Date;
    _count: any;
  }
  export interface OrderColor {
    id: string;
    orderId: string;
    order: Order;
    colorId: string;
    color: RefColor;
    productName: string | null;
    position: number;
    quantities: StageQuantity[];
    cartons: Carton[];
    _count: any;
  }
  export interface OrderSize {
    id: string;
    orderId: string;
    order: Order;
    sizeId: string;
    size: RefSize;
    position: number;
    quantities: StageQuantity[];
    cartons: Carton[];
    _count: any;
  }
  export interface StageQuantity {
    id: string;
    orderId: string;
    order: Order;
    orderColorId: string;
    orderColor: OrderColor;
    orderSizeId: string;
    orderSize: OrderSize;
    ledger: QtyLedger;
    qty: number;
    updatedAt: Date;
    _count: any;
  }
  export interface OrderNote {
    id: string;
    orderId: string;
    order: Order;
    kind: NoteKind;
    body: string;
    updatedAt: Date;
    _count: any;
  }
  export interface OrderStage {
    id: string;
    orderId: string;
    order: Order;
    stageKey: StageKey;
    startedAt: Date | null;
    dueDate: Date | null;
    completedAt: Date | null;
    notes: string | null;
    statusOverride: StageStatus | null;
    notRequiredReason: string | null;
    completedById: string | null;
    completedBy: User | null;
    tasks: Task[];
    attachments: Attachment[];
    updatedAt: Date;
    _count: any;
  }
  export interface TaskTemplate {
    key: string;
    stageKey: StageKey;
    department: Department;
    title: string;
    requirementEn: string;
    requirementAr: string;
    estimatedMinutes: number;
    sequence: number;
    priority: Priority;
    critical: boolean;
    active: boolean;
    position: number;
    tasks: Task[];
    _count: any;
  }
  export interface Task {
    id: string;
    orderId: string;
    order: Order;
    orderStageId: string;
    orderStage: OrderStage;
    stageKey: StageKey;
    templateKey: string | null;
    template: TaskTemplate | null;
    title: string;
    requirementEn: string | null;
    requirementAr: string | null;
    department: Department;
    sequence: number;
    estimatedMinutes: number | null;
    actualMinutes: number | null;
    status: TaskStatus;
    priority: Priority;
    dueDate: Date | null;
    startedAt: Date | null;
    completedAt: Date | null;
    notes: string | null;
    blockedReason: string | null;
    assigneeId: string | null;
    assignee: User | null;
    completedById: string | null;
    completedBy: User | null;
    blockedByTaskId: string | null;
    blockedBy: Task | null;
    blocking: Task[];
    isCorrectiveAction: boolean;
    sourceAuditId: string | null;
    comments: TaskComment[];
    attachments: Attachment[];
    createdAt: Date;
    updatedAt: Date;
    _count: any;
  }
  export interface TaskComment {
    id: string;
    taskId: string;
    task: Task;
    authorId: string;
    author: User;
    body: string;
    createdAt: Date;
    _count: any;
  }
  export interface BomItem {
    id: string;
    orderId: string;
    order: Order;
    category: BomCategory;
    position: string | null;
    item: string;
    description: string | null;
    colorId: string | null;
    color: RefColor | null;
    colorText: string | null;
    materialId: string | null;
    material: Material | null;
    consumptionPerPiece: Prisma.Decimal | null;
    requiredQty: Prisma.Decimal;
    unit: string;
    issuedQty: Prisma.Decimal;
    issuedByName: string | null;
    issuedToName: string | null;
    issuedAt: Date | null;
    purchaseOrderRef: string | null;
    notes: string | null;
    position_: number;
    issues: MaterialIssue[];
    movements: MaterialMovement[];
    reservations: MaterialReservation[];
    createdAt: Date;
    updatedAt: Date;
    _count: any;
  }
  export interface MaterialIssue {
    id: string;
    orderId: string;
    order: Order;
    bomItemId: string;
    bomItem: BomItem;
    qty: Prisma.Decimal;
    unit: string;
    issuedAt: Date;
    issuedById: string | null;
    issuedBy: User | null;
    issuedToId: string | null;
    issuedTo: User | null;
    issuedToName: string | null;
    notes: string | null;
    _count: any;
  }
  export interface StockRecord {
    id: string;
    orderId: string;
    colorName: string;
    sizeName: string;
    availableQty: number;
    reservedQty: number;
    usedQty: number;
    location: string | null;
    notes: string | null;
    recordedAt: Date;
    _count: any;
  }
  export interface Material {
    id: string;
    code: string | null;
    name: string;
    type: MaterialType;
    description: string | null;
    colorName: string | null;
    widthCm: Prisma.Decimal | null;
    composition: string | null;
    gsm: number | null;
    sizeLabel: string | null;
    unit: UnitOfMeasure;
    supplierName: string | null;
    supplierRef: string | null;
    minimumQty: Prisma.Decimal | null;
    unitCostUsd: Prisma.Decimal | null;
    notes: string | null;
    active: boolean;
    stock: MaterialStock[];
    movements: MaterialMovement[];
    reservations: MaterialReservation[];
    bomItems: BomItem[];
    createdAt: Date;
    updatedAt: Date;
    _count: any;
  }
  export interface InventoryLocation {
    id: string;
    name: string;
    code: string | null;
    kind: string;
    notes: string | null;
    active: boolean;
    stock: MaterialStock[];
    movements: MaterialMovement[];
    createdAt: Date;
    _count: any;
  }
  export interface MaterialStock {
    id: string;
    materialId: string;
    material: Material;
    locationId: string | null;
    location: InventoryLocation | null;
    physicalQty: Prisma.Decimal;
    binRef: string | null;
    updatedAt: Date;
    _count: any;
  }
  export interface MaterialMovement {
    id: string;
    materialId: string;
    material: Material;
    locationId: string | null;
    location: InventoryLocation | null;
    type: MovementType;
    qty: Prisma.Decimal;
    unit: UnitOfMeasure;
    balanceAfter: Prisma.Decimal;
    orderId: string | null;
    order: Order | null;
    reservationId: string | null;
    reservation: MaterialReservation | null;
    bomItemId: string | null;
    bomItem: BomItem | null;
    reason: string | null;
    batchLot: string | null;
    reference: string | null;
    stage: StageKey | null;
    actorId: string | null;
    actor: User | null;
    actorName: string;
    occurredAt: Date;
    createdAt: Date;
    _count: any;
  }
  export interface MaterialReservation {
    id: string;
    materialId: string;
    material: Material;
    orderId: string;
    order: Order;
    bomItemId: string | null;
    bomItem: BomItem | null;
    qty: Prisma.Decimal;
    consumedQty: Prisma.Decimal;
    unit: UnitOfMeasure;
    status: ReservationStatus;
    reservedById: string | null;
    reservedBy: User | null;
    releasedAt: Date | null;
    releaseReason: string | null;
    notes: string | null;
    movements: MaterialMovement[];
    createdAt: Date;
    updatedAt: Date;
    _count: any;
  }
  export interface CuttingRecord {
    id: string;
    orderId: string;
    order: Order;
    cutDate: Date | null;
    cuttingTeam: string | null;
    cutByName: string | null;
    inspectedByName: string | null;
    numberingByName: string | null;
    bundledByName: string | null;
    approvedByName: string | null;
    actualCutQty: number | null;
    fabricUsedM: Prisma.Decimal | null;
    notes: string | null;
    createdAt: Date;
    updatedAt: Date;
    _count: any;
  }
  export interface Marker {
    id: string;
    orderId: string;
    order: Order;
    markerNumber: string | null;
    fabricName: string;
    fabricColor: string | null;
    panel: string;
    sizeRatio: string;
    layers: number;
    markerLengthM: Prisma.Decimal;
    totalLengthM: Prisma.Decimal | null;
    nestPcs: number | null;
    efficiencyPct: Prisma.Decimal | null;
    maxLayer: number | null;
    notes: string | null;
    position: number;
    createdAt: Date;
    updatedAt: Date;
    _count: any;
  }
  export interface FabricRecord {
    id: string;
    orderId: string;
    order: Order;
    fabricName: string;
    colorName: string | null;
    fabricType: string | null;
    composition: string | null;
    supplier: string | null;
    requiredM: Prisma.Decimal | null;
    availableM: Prisma.Decimal | null;
    issuedM: Prisma.Decimal | null;
    actualConsumptionM: Prisma.Decimal | null;
    responsibleName: string | null;
    recordedAt: Date;
    notes: string | null;
    _count: any;
  }
  export interface ExternalOperation {
    id: string;
    orderId: string;
    order: Order;
    externalFactoryId: string | null;
    externalFactory: Factory | null;
    externalReference: string | null;
    operationType: string;
    operationTypeAr: string | null;
    operationSort: string | null;
    qty: number;
    unitRate: Prisma.Decimal | null;
    unitPriceUsd: Prisma.Decimal | null;
    sentDate: Date | null;
    expectedReturnDate: Date | null;
    actualReturnDate: Date | null;
    status: ExternalOpStatus;
    requiresApproval: boolean;
    approvalId: string | null;
    approval: Approval | null;
    notes: string | null;
    colorIds: string[];
    attachments: Attachment[];
    createdAt: Date;
    updatedAt: Date;
    _count: any;
  }
  export interface Approval {
    id: string;
    orderId: string;
    order: Order;
    type: ApprovalType;
    status: ApprovalStatus;
    blocking: boolean;
    requestedDate: Date | null;
    requestedById: string | null;
    requestedBy: User | null;
    sentTo: string | null;
    approvedDate: Date | null;
    approvedByName: string | null;
    comment: string | null;
    externalOperation: ExternalOperation | null;
    attachments: Attachment[];
    createdAt: Date;
    updatedAt: Date;
    _count: any;
  }
  export interface CustomInstruction {
    id: string;
    orderId: string;
    order: Order;
    title: string;
    body: string;
    visibleTo: Department[];
    position: number;
    attachments: Attachment[];
    createdAt: Date;
    updatedAt: Date;
    _count: any;
  }
  export interface ProductionRecord {
    id: string;
    orderId: string;
    order: Order;
    date: Date;
    operation: ProductionOperation;
    qty: number;
    line: string | null;
    team: string | null;
    notes: string | null;
    recordedById: string | null;
    recordedBy: User | null;
    createdAt: Date;
    _count: any;
  }
  export interface QualityAudit {
    id: string;
    orderId: string;
    order: Order;
    inspectionDate: Date;
    factoryId: string | null;
    factory: Factory | null;
    auditType: AuditType;
    availableQty: number;
    sampleSize: number | null;
    acceptedQty: number | null;
    rejectedQty: number | null;
    result: AuditResult;
    overridden: boolean;
    remarks: string | null;
    correctiveAction: string | null;
    correctiveActionClosed: boolean;
    reinspectionOf: string | null;
    reinspectFor: string | null;
    auditorId: string | null;
    auditor: User | null;
    factoryRepName: string | null;
    colorsInspected: string[];
    sizesInspected: string[];
    defects: QualityDefect[];
    attachments: Attachment[];
    createdAt: Date;
    updatedAt: Date;
    _count: any;
  }
  export interface QualityDefect {
    id: string;
    auditId: string;
    audit: QualityAudit;
    category: DefectCategory;
    qty: number;
    comment: string | null;
    isReinspection: boolean;
    _count: any;
  }
  export interface PackingList {
    id: string;
    orderId: string;
    order: Order;
    reference: string | null;
    approved: boolean;
    approvedAt: Date | null;
    approvedByName: string | null;
    notes: string | null;
    cartons: Carton[];
    createdAt: Date;
    updatedAt: Date;
    _count: any;
  }
  export interface Carton {
    id: string;
    packingListId: string;
    packingList: PackingList;
    cartonNumber: string;
    cartonSize: string | null;
    orderColorId: string | null;
    orderColor: OrderColor | null;
    orderSizeId: string | null;
    orderSize: OrderSize | null;
    qty: number;
    grossWeightKg: Prisma.Decimal | null;
    netWeightKg: Prisma.Decimal | null;
    position: number;
    _count: any;
  }
  export interface Shipment {
    id: string;
    orderId: string;
    order: Order;
    method: string | null;
    status: ShipmentStatus;
    qty: number;
    promisedShippingDate: Date | null;
    requiredDeliveryDate: Date | null;
    actualShippingDate: Date | null;
    deliveredDate: Date | null;
    trackingNumber: string | null;
    carrier: string | null;
    awbNumber: string | null;
    containerSeal: string | null;
    vesselVoyage: string | null;
    finalDestination: string | null;
    notes: string | null;
    overrideApproved: boolean;
    overrideReason: string | null;
    attachments: Attachment[];
    createdAt: Date;
    updatedAt: Date;
    _count: any;
  }
  export interface CostingRecord {
    id: string;
    orderId: string;
    order: Order;
    costingDate: Date | null;
    dollarRate: Prisma.Decimal;
    dailyCostEgp: Prisma.Decimal | null;
    machineCount: number | null;
    machineDaysUsed: number | null;
    daysInLine: number | null;
    productionLineMachines: Prisma.JsonValue | null;
    sublimationCostUsd: Prisma.Decimal | null;
    embroideryCostUsd: Prisma.Decimal | null;
    externalOpCostUsd: Prisma.Decimal | null;
    notes: string | null;
    lines: CostLine[];
    createdAt: Date;
    updatedAt: Date;
    _count: any;
  }
  export interface CostLine {
    id: string;
    costingId: string;
    costing: CostingRecord;
    group: CostGroup;
    label: string;
    quantity: Prisma.Decimal | null;
    unit: string;
    unitPriceUsd: Prisma.Decimal | null;
    unitPriceEgp: Prisma.Decimal | null;
    position: number;
    _count: any;
  }
  export interface ProformaInvoice {
    id: string;
    orderId: string;
    order: Order;
    number: string | null;
    date: Date;
    consignee: string | null;
    billingAddress: string | null;
    email: string | null;
    vesselVoyage: string | null;
    containerSeal: string | null;
    shippingDate: Date | null;
    shipmentFrom: string | null;
    shipmentTo: string | null;
    consolidatingVendor: string | null;
    currency: string;
    terms: string | null;
    sentAt: Date | null;
    preparedById: string | null;
    preparedBy: User | null;
    lines: ProformaInvoiceLine[];
    createdAt: Date;
    updatedAt: Date;
    _count: any;
  }
  export interface ProformaInvoiceLine {
    id: string;
    invoiceId: string;
    invoice: ProformaInvoice;
    description: string;
    quantity: Prisma.Decimal | null;
    unit: string;
    unitPrice: Prisma.Decimal | null;
    position: number;
    _count: any;
  }
  export interface Attachment {
    id: string;
    orderId: string | null;
    order: Order | null;
    orderStageId: string | null;
    orderStage: OrderStage | null;
    stageKey: StageKey | null;
    taskId: string | null;
    task: Task | null;
    approvalId: string | null;
    approval: Approval | null;
    externalOperationId: string | null;
    externalOperation: ExternalOperation | null;
    qualityAuditId: string | null;
    qualityAudit: QualityAudit | null;
    shipmentId: string | null;
    shipment: Shipment | null;
    customInstructionId: string | null;
    customInstruction: CustomInstruction | null;
    fileName: string;
    documentType: DocumentType;
    mimeType: string;
    sizeBytes: number;
    storageKey: string;
    storageDriver: string;
    version: number;
    checksum: string | null;
    uploadedById: string;
    uploadedBy: User;
    createdAt: Date;
    _count: any;
  }
  export interface ActivityLog {
    id: string;
    orderId: string | null;
    order: Order | null;
    actorId: string | null;
    actor: User | null;
    actorName: string;
    action: string;
    summary: string;
    entityType: string | null;
    entityId: string | null;
    meta: Prisma.JsonValue | null;
    createdAt: Date;
    _count: any;
  }
  export interface AuditTrail {
    id: string;
    orderId: string | null;
    order: Order | null;
    entityType: string;
    entityId: string;
    action: string;
    field: string;
    oldValue: string | null;
    newValue: string | null;
    actorId: string | null;
    actor: User | null;
    actorName: string;
    reason: string | null;
    createdAt: Date;
    _count: any;
  }
  export interface Notification {
    id: string;
    userId: string;
    user: User;
    orderId: string | null;
    order: Order | null;
    type: NotificationType;
    title: string;
    body: string | null;
    link: string | null;
    priority: NotificationPriority;
    changeEventId: string | null;
    changeEvent: ChangeEvent | null;
    readAt: Date | null;
    createdAt: Date;
    _count: any;
  }
  export interface ChangeEvent {
    id: string;
    entityType: string;
    entityId: string;
    action: string;
    category: ChangeCategory;
    subject: string | null;
    summary: string;
    priority: NotificationPriority;
    orderId: string | null;
    order: Order | null;
    actorId: string | null;
    actor: User | null;
    actorName: string;
    link: string | null;
    reason: string | null;
    fields: ChangeEventField[];
    notifications: Notification[];
    emails: EmailDelivery[];
    createdAt: Date;
    _count: any;
  }
  export interface ChangeEventField {
    id: string;
    changeEventId: string;
    changeEvent: ChangeEvent;
    field: string;
    label: string;
    oldValue: string | null;
    newValue: string | null;
    position: number;
    _count: any;
  }
  export interface EmailDelivery {
    id: string;
    changeEventId: string | null;
    changeEvent: ChangeEvent | null;
    recipients: string[];
    subject: string;
    bodyHtml: string;
    bodyText: string;
    status: EmailStatus;
    attempts: number;
    lastError: string | null;
    nextAttemptAt: Date;
    sentAt: Date | null;
    createdAt: Date;
    updatedAt: Date;
    _count: any;
  }
  export interface ImportJob {
    id: string;
    fileName: string;
    storageKey: string;
    status: ImportStatus;
    profile: string | null;
    profileConfidence: Prisma.Decimal | null;
    detectedSheets: Prisma.JsonValue | null;
    mappings: Prisma.JsonValue | null;
    issues: Prisma.JsonValue | null;
    preview: Prisma.JsonValue | null;
    createdOrderId: string | null;
    errorMessage: string | null;
    uploadedById: string;
    uploadedBy: User;
    createdAt: Date;
    committedAt: Date | null;
    _count: any;
  }
  export interface SavedColumnMapping {
    id: string;
    clientId: string | null;
    client: Client | null;
    label: string;
    headerFingerprint: string;
    mapping: Prisma.JsonValue;
    useCount: number;
    lastUsedAt: Date | null;
    createdById: string | null;
    createdBy: User | null;
    createdAt: Date;
    updatedAt: Date;
    _count: any;
  }

  export namespace Prisma {
    export class Decimal {
      constructor(v: string | number | Decimal);
      toString(): string;
      toNumber(): number;
    }
    export type JsonValue = string | number | boolean | null | JsonValue[] | { [k: string]: JsonValue };
    export type InputJsonValue = JsonValue;
    export type JsonObject = { [k: string]: JsonValue };

    export class PrismaClientKnownRequestError extends Error {
      code: string;
      meta?: Record<string, unknown>;
    }
    export class PrismaClientValidationError extends Error {}

    export type Middleware = (params: MiddlewareParams, next: (p: MiddlewareParams) => Promise<any>) => Promise<any>;
    export interface MiddlewareParams {
      model?: string; action: string; args: any; dataPath: string[]; runInTransaction: boolean;
    }

    export type TransactionClient = Omit<PrismaClient, '$transaction' | '$connect' | '$disconnect' | '$use'>;
    export type RoleGetPayload<T = any> = Role & Record<string, any>;
    export type RoleInclude = Record<string, any>;
    export type RoleWhereInput = Record<string, any>;
    export type RoleCreateManyInput = Record<string, any>;
    export type RoleCreateInput = Record<string, any>;
    export type RoleUpdateInput = Record<string, any>;
    export type UserGetPayload<T = any> = User & Record<string, any>;
    export type UserInclude = Record<string, any>;
    export type UserWhereInput = Record<string, any>;
    export type UserCreateManyInput = Record<string, any>;
    export type UserCreateInput = Record<string, any>;
    export type UserUpdateInput = Record<string, any>;
    export type ClientGetPayload<T = any> = Client & Record<string, any>;
    export type ClientInclude = Record<string, any>;
    export type ClientWhereInput = Record<string, any>;
    export type ClientCreateManyInput = Record<string, any>;
    export type ClientCreateInput = Record<string, any>;
    export type ClientUpdateInput = Record<string, any>;
    export type FactoryGetPayload<T = any> = Factory & Record<string, any>;
    export type FactoryInclude = Record<string, any>;
    export type FactoryWhereInput = Record<string, any>;
    export type FactoryCreateManyInput = Record<string, any>;
    export type FactoryCreateInput = Record<string, any>;
    export type FactoryUpdateInput = Record<string, any>;
    export type RefColorGetPayload<T = any> = RefColor & Record<string, any>;
    export type RefColorInclude = Record<string, any>;
    export type RefColorWhereInput = Record<string, any>;
    export type RefColorCreateManyInput = Record<string, any>;
    export type RefColorCreateInput = Record<string, any>;
    export type RefColorUpdateInput = Record<string, any>;
    export type RefSizeGetPayload<T = any> = RefSize & Record<string, any>;
    export type RefSizeInclude = Record<string, any>;
    export type RefSizeWhereInput = Record<string, any>;
    export type RefSizeCreateManyInput = Record<string, any>;
    export type RefSizeCreateInput = Record<string, any>;
    export type RefSizeUpdateInput = Record<string, any>;
    export type RefValueGetPayload<T = any> = RefValue & Record<string, any>;
    export type RefValueInclude = Record<string, any>;
    export type RefValueWhereInput = Record<string, any>;
    export type RefValueCreateManyInput = Record<string, any>;
    export type RefValueCreateInput = Record<string, any>;
    export type RefValueUpdateInput = Record<string, any>;
    export type OrderGetPayload<T = any> = Order & Record<string, any>;
    export type OrderInclude = Record<string, any>;
    export type OrderWhereInput = Record<string, any>;
    export type OrderCreateManyInput = Record<string, any>;
    export type OrderCreateInput = Record<string, any>;
    export type OrderUpdateInput = Record<string, any>;
    export type OrderColorGetPayload<T = any> = OrderColor & Record<string, any>;
    export type OrderColorInclude = Record<string, any>;
    export type OrderColorWhereInput = Record<string, any>;
    export type OrderColorCreateManyInput = Record<string, any>;
    export type OrderColorCreateInput = Record<string, any>;
    export type OrderColorUpdateInput = Record<string, any>;
    export type OrderSizeGetPayload<T = any> = OrderSize & Record<string, any>;
    export type OrderSizeInclude = Record<string, any>;
    export type OrderSizeWhereInput = Record<string, any>;
    export type OrderSizeCreateManyInput = Record<string, any>;
    export type OrderSizeCreateInput = Record<string, any>;
    export type OrderSizeUpdateInput = Record<string, any>;
    export type StageQuantityGetPayload<T = any> = StageQuantity & Record<string, any>;
    export type StageQuantityInclude = Record<string, any>;
    export type StageQuantityWhereInput = Record<string, any>;
    export type StageQuantityCreateManyInput = Record<string, any>;
    export type StageQuantityCreateInput = Record<string, any>;
    export type StageQuantityUpdateInput = Record<string, any>;
    export type OrderNoteGetPayload<T = any> = OrderNote & Record<string, any>;
    export type OrderNoteInclude = Record<string, any>;
    export type OrderNoteWhereInput = Record<string, any>;
    export type OrderNoteCreateManyInput = Record<string, any>;
    export type OrderNoteCreateInput = Record<string, any>;
    export type OrderNoteUpdateInput = Record<string, any>;
    export type OrderStageGetPayload<T = any> = OrderStage & Record<string, any>;
    export type OrderStageInclude = Record<string, any>;
    export type OrderStageWhereInput = Record<string, any>;
    export type OrderStageCreateManyInput = Record<string, any>;
    export type OrderStageCreateInput = Record<string, any>;
    export type OrderStageUpdateInput = Record<string, any>;
    export type TaskTemplateGetPayload<T = any> = TaskTemplate & Record<string, any>;
    export type TaskTemplateInclude = Record<string, any>;
    export type TaskTemplateWhereInput = Record<string, any>;
    export type TaskTemplateCreateManyInput = Record<string, any>;
    export type TaskTemplateCreateInput = Record<string, any>;
    export type TaskTemplateUpdateInput = Record<string, any>;
    export type TaskGetPayload<T = any> = Task & Record<string, any>;
    export type TaskInclude = Record<string, any>;
    export type TaskWhereInput = Record<string, any>;
    export type TaskCreateManyInput = Record<string, any>;
    export type TaskCreateInput = Record<string, any>;
    export type TaskUpdateInput = Record<string, any>;
    export type TaskCommentGetPayload<T = any> = TaskComment & Record<string, any>;
    export type TaskCommentInclude = Record<string, any>;
    export type TaskCommentWhereInput = Record<string, any>;
    export type TaskCommentCreateManyInput = Record<string, any>;
    export type TaskCommentCreateInput = Record<string, any>;
    export type TaskCommentUpdateInput = Record<string, any>;
    export type BomItemGetPayload<T = any> = BomItem & Record<string, any>;
    export type BomItemInclude = Record<string, any>;
    export type BomItemWhereInput = Record<string, any>;
    export type BomItemCreateManyInput = Record<string, any>;
    export type BomItemCreateInput = Record<string, any>;
    export type BomItemUpdateInput = Record<string, any>;
    export type MaterialIssueGetPayload<T = any> = MaterialIssue & Record<string, any>;
    export type MaterialIssueInclude = Record<string, any>;
    export type MaterialIssueWhereInput = Record<string, any>;
    export type MaterialIssueCreateManyInput = Record<string, any>;
    export type MaterialIssueCreateInput = Record<string, any>;
    export type MaterialIssueUpdateInput = Record<string, any>;
    export type StockRecordGetPayload<T = any> = StockRecord & Record<string, any>;
    export type StockRecordInclude = Record<string, any>;
    export type StockRecordWhereInput = Record<string, any>;
    export type StockRecordCreateManyInput = Record<string, any>;
    export type StockRecordCreateInput = Record<string, any>;
    export type StockRecordUpdateInput = Record<string, any>;
    export type MaterialGetPayload<T = any> = Material & Record<string, any>;
    export type MaterialInclude = Record<string, any>;
    export type MaterialWhereInput = Record<string, any>;
    export type MaterialCreateManyInput = Record<string, any>;
    export type MaterialCreateInput = Record<string, any>;
    export type MaterialUpdateInput = Record<string, any>;
    export type InventoryLocationGetPayload<T = any> = InventoryLocation & Record<string, any>;
    export type InventoryLocationInclude = Record<string, any>;
    export type InventoryLocationWhereInput = Record<string, any>;
    export type InventoryLocationCreateManyInput = Record<string, any>;
    export type InventoryLocationCreateInput = Record<string, any>;
    export type InventoryLocationUpdateInput = Record<string, any>;
    export type MaterialStockGetPayload<T = any> = MaterialStock & Record<string, any>;
    export type MaterialStockInclude = Record<string, any>;
    export type MaterialStockWhereInput = Record<string, any>;
    export type MaterialStockCreateManyInput = Record<string, any>;
    export type MaterialStockCreateInput = Record<string, any>;
    export type MaterialStockUpdateInput = Record<string, any>;
    export type MaterialMovementGetPayload<T = any> = MaterialMovement & Record<string, any>;
    export type MaterialMovementInclude = Record<string, any>;
    export type MaterialMovementWhereInput = Record<string, any>;
    export type MaterialMovementCreateManyInput = Record<string, any>;
    export type MaterialMovementCreateInput = Record<string, any>;
    export type MaterialMovementUpdateInput = Record<string, any>;
    export type MaterialReservationGetPayload<T = any> = MaterialReservation & Record<string, any>;
    export type MaterialReservationInclude = Record<string, any>;
    export type MaterialReservationWhereInput = Record<string, any>;
    export type MaterialReservationCreateManyInput = Record<string, any>;
    export type MaterialReservationCreateInput = Record<string, any>;
    export type MaterialReservationUpdateInput = Record<string, any>;
    export type CuttingRecordGetPayload<T = any> = CuttingRecord & Record<string, any>;
    export type CuttingRecordInclude = Record<string, any>;
    export type CuttingRecordWhereInput = Record<string, any>;
    export type CuttingRecordCreateManyInput = Record<string, any>;
    export type CuttingRecordCreateInput = Record<string, any>;
    export type CuttingRecordUpdateInput = Record<string, any>;
    export type MarkerGetPayload<T = any> = Marker & Record<string, any>;
    export type MarkerInclude = Record<string, any>;
    export type MarkerWhereInput = Record<string, any>;
    export type MarkerCreateManyInput = Record<string, any>;
    export type MarkerCreateInput = Record<string, any>;
    export type MarkerUpdateInput = Record<string, any>;
    export type FabricRecordGetPayload<T = any> = FabricRecord & Record<string, any>;
    export type FabricRecordInclude = Record<string, any>;
    export type FabricRecordWhereInput = Record<string, any>;
    export type FabricRecordCreateManyInput = Record<string, any>;
    export type FabricRecordCreateInput = Record<string, any>;
    export type FabricRecordUpdateInput = Record<string, any>;
    export type ExternalOperationGetPayload<T = any> = ExternalOperation & Record<string, any>;
    export type ExternalOperationInclude = Record<string, any>;
    export type ExternalOperationWhereInput = Record<string, any>;
    export type ExternalOperationCreateManyInput = Record<string, any>;
    export type ExternalOperationCreateInput = Record<string, any>;
    export type ExternalOperationUpdateInput = Record<string, any>;
    export type ApprovalGetPayload<T = any> = Approval & Record<string, any>;
    export type ApprovalInclude = Record<string, any>;
    export type ApprovalWhereInput = Record<string, any>;
    export type ApprovalCreateManyInput = Record<string, any>;
    export type ApprovalCreateInput = Record<string, any>;
    export type ApprovalUpdateInput = Record<string, any>;
    export type CustomInstructionGetPayload<T = any> = CustomInstruction & Record<string, any>;
    export type CustomInstructionInclude = Record<string, any>;
    export type CustomInstructionWhereInput = Record<string, any>;
    export type CustomInstructionCreateManyInput = Record<string, any>;
    export type CustomInstructionCreateInput = Record<string, any>;
    export type CustomInstructionUpdateInput = Record<string, any>;
    export type ProductionRecordGetPayload<T = any> = ProductionRecord & Record<string, any>;
    export type ProductionRecordInclude = Record<string, any>;
    export type ProductionRecordWhereInput = Record<string, any>;
    export type ProductionRecordCreateManyInput = Record<string, any>;
    export type ProductionRecordCreateInput = Record<string, any>;
    export type ProductionRecordUpdateInput = Record<string, any>;
    export type QualityAuditGetPayload<T = any> = QualityAudit & Record<string, any>;
    export type QualityAuditInclude = Record<string, any>;
    export type QualityAuditWhereInput = Record<string, any>;
    export type QualityAuditCreateManyInput = Record<string, any>;
    export type QualityAuditCreateInput = Record<string, any>;
    export type QualityAuditUpdateInput = Record<string, any>;
    export type QualityDefectGetPayload<T = any> = QualityDefect & Record<string, any>;
    export type QualityDefectInclude = Record<string, any>;
    export type QualityDefectWhereInput = Record<string, any>;
    export type QualityDefectCreateManyInput = Record<string, any>;
    export type QualityDefectCreateInput = Record<string, any>;
    export type QualityDefectUpdateInput = Record<string, any>;
    export type PackingListGetPayload<T = any> = PackingList & Record<string, any>;
    export type PackingListInclude = Record<string, any>;
    export type PackingListWhereInput = Record<string, any>;
    export type PackingListCreateManyInput = Record<string, any>;
    export type PackingListCreateInput = Record<string, any>;
    export type PackingListUpdateInput = Record<string, any>;
    export type CartonGetPayload<T = any> = Carton & Record<string, any>;
    export type CartonInclude = Record<string, any>;
    export type CartonWhereInput = Record<string, any>;
    export type CartonCreateManyInput = Record<string, any>;
    export type CartonCreateInput = Record<string, any>;
    export type CartonUpdateInput = Record<string, any>;
    export type ShipmentGetPayload<T = any> = Shipment & Record<string, any>;
    export type ShipmentInclude = Record<string, any>;
    export type ShipmentWhereInput = Record<string, any>;
    export type ShipmentCreateManyInput = Record<string, any>;
    export type ShipmentCreateInput = Record<string, any>;
    export type ShipmentUpdateInput = Record<string, any>;
    export type CostingRecordGetPayload<T = any> = CostingRecord & Record<string, any>;
    export type CostingRecordInclude = Record<string, any>;
    export type CostingRecordWhereInput = Record<string, any>;
    export type CostingRecordCreateManyInput = Record<string, any>;
    export type CostingRecordCreateInput = Record<string, any>;
    export type CostingRecordUpdateInput = Record<string, any>;
    export type CostLineGetPayload<T = any> = CostLine & Record<string, any>;
    export type CostLineInclude = Record<string, any>;
    export type CostLineWhereInput = Record<string, any>;
    export type CostLineCreateManyInput = Record<string, any>;
    export type CostLineCreateInput = Record<string, any>;
    export type CostLineUpdateInput = Record<string, any>;
    export type ProformaInvoiceGetPayload<T = any> = ProformaInvoice & Record<string, any>;
    export type ProformaInvoiceInclude = Record<string, any>;
    export type ProformaInvoiceWhereInput = Record<string, any>;
    export type ProformaInvoiceCreateManyInput = Record<string, any>;
    export type ProformaInvoiceCreateInput = Record<string, any>;
    export type ProformaInvoiceUpdateInput = Record<string, any>;
    export type ProformaInvoiceLineGetPayload<T = any> = ProformaInvoiceLine & Record<string, any>;
    export type ProformaInvoiceLineInclude = Record<string, any>;
    export type ProformaInvoiceLineWhereInput = Record<string, any>;
    export type ProformaInvoiceLineCreateManyInput = Record<string, any>;
    export type ProformaInvoiceLineCreateInput = Record<string, any>;
    export type ProformaInvoiceLineUpdateInput = Record<string, any>;
    export type AttachmentGetPayload<T = any> = Attachment & Record<string, any>;
    export type AttachmentInclude = Record<string, any>;
    export type AttachmentWhereInput = Record<string, any>;
    export type AttachmentCreateManyInput = Record<string, any>;
    export type AttachmentCreateInput = Record<string, any>;
    export type AttachmentUpdateInput = Record<string, any>;
    export type ActivityLogGetPayload<T = any> = ActivityLog & Record<string, any>;
    export type ActivityLogInclude = Record<string, any>;
    export type ActivityLogWhereInput = Record<string, any>;
    export type ActivityLogCreateManyInput = Record<string, any>;
    export type ActivityLogCreateInput = Record<string, any>;
    export type ActivityLogUpdateInput = Record<string, any>;
    export type AuditTrailGetPayload<T = any> = AuditTrail & Record<string, any>;
    export type AuditTrailInclude = Record<string, any>;
    export type AuditTrailWhereInput = Record<string, any>;
    export type AuditTrailCreateManyInput = Record<string, any>;
    export type AuditTrailCreateInput = Record<string, any>;
    export type AuditTrailUpdateInput = Record<string, any>;
    export type NotificationGetPayload<T = any> = Notification & Record<string, any>;
    export type NotificationInclude = Record<string, any>;
    export type NotificationWhereInput = Record<string, any>;
    export type NotificationCreateManyInput = Record<string, any>;
    export type NotificationCreateInput = Record<string, any>;
    export type NotificationUpdateInput = Record<string, any>;
    export type ChangeEventGetPayload<T = any> = ChangeEvent & Record<string, any>;
    export type ChangeEventInclude = Record<string, any>;
    export type ChangeEventWhereInput = Record<string, any>;
    export type ChangeEventCreateManyInput = Record<string, any>;
    export type ChangeEventCreateInput = Record<string, any>;
    export type ChangeEventUpdateInput = Record<string, any>;
    export type ChangeEventFieldGetPayload<T = any> = ChangeEventField & Record<string, any>;
    export type ChangeEventFieldInclude = Record<string, any>;
    export type ChangeEventFieldWhereInput = Record<string, any>;
    export type ChangeEventFieldCreateManyInput = Record<string, any>;
    export type ChangeEventFieldCreateInput = Record<string, any>;
    export type ChangeEventFieldUpdateInput = Record<string, any>;
    export type EmailDeliveryGetPayload<T = any> = EmailDelivery & Record<string, any>;
    export type EmailDeliveryInclude = Record<string, any>;
    export type EmailDeliveryWhereInput = Record<string, any>;
    export type EmailDeliveryCreateManyInput = Record<string, any>;
    export type EmailDeliveryCreateInput = Record<string, any>;
    export type EmailDeliveryUpdateInput = Record<string, any>;
    export type ImportJobGetPayload<T = any> = ImportJob & Record<string, any>;
    export type ImportJobInclude = Record<string, any>;
    export type ImportJobWhereInput = Record<string, any>;
    export type ImportJobCreateManyInput = Record<string, any>;
    export type ImportJobCreateInput = Record<string, any>;
    export type ImportJobUpdateInput = Record<string, any>;
    export type SavedColumnMappingGetPayload<T = any> = SavedColumnMapping & Record<string, any>;
    export type SavedColumnMappingInclude = Record<string, any>;
    export type SavedColumnMappingWhereInput = Record<string, any>;
    export type SavedColumnMappingCreateManyInput = Record<string, any>;
    export type SavedColumnMappingCreateInput = Record<string, any>;
    export type SavedColumnMappingUpdateInput = Record<string, any>;
    export type EnumPriorityFilter = { equals?: any };
  }

  interface Delegate<M> {
    findMany(args?: any): Promise<any[]>;
    findUnique(args: any): Promise<M | null>;
    findUniqueOrThrow(args: any): Promise<any>;
    findFirst(args?: any): Promise<any | null>;
    findFirstOrThrow(args?: any): Promise<any>;
    create(args: any): Promise<any>;
    createMany(args: any): Promise<{ count: number }>;
    update(args: any): Promise<any>;
    updateMany(args: any): Promise<{ count: number }>;
    upsert(args: any): Promise<any>;
    delete(args: any): Promise<any>;
    deleteMany(args?: any): Promise<{ count: number }>;
    count(args?: any): Promise<number>;
    aggregate(args?: any): Promise<any>;
    groupBy(args: any): Promise<any[]>;
  }

  export class PrismaClient {
    constructor(opts?: any);
    role: Delegate<Role>;
    user: Delegate<User>;
    client: Delegate<Client>;
    factory: Delegate<Factory>;
    refColor: Delegate<RefColor>;
    refSize: Delegate<RefSize>;
    refValue: Delegate<RefValue>;
    order: Delegate<Order>;
    orderColor: Delegate<OrderColor>;
    orderSize: Delegate<OrderSize>;
    stageQuantity: Delegate<StageQuantity>;
    orderNote: Delegate<OrderNote>;
    orderStage: Delegate<OrderStage>;
    taskTemplate: Delegate<TaskTemplate>;
    task: Delegate<Task>;
    taskComment: Delegate<TaskComment>;
    bomItem: Delegate<BomItem>;
    materialIssue: Delegate<MaterialIssue>;
    stockRecord: Delegate<StockRecord>;
    material: Delegate<Material>;
    inventoryLocation: Delegate<InventoryLocation>;
    materialStock: Delegate<MaterialStock>;
    materialMovement: Delegate<MaterialMovement>;
    materialReservation: Delegate<MaterialReservation>;
    cuttingRecord: Delegate<CuttingRecord>;
    marker: Delegate<Marker>;
    fabricRecord: Delegate<FabricRecord>;
    externalOperation: Delegate<ExternalOperation>;
    approval: Delegate<Approval>;
    customInstruction: Delegate<CustomInstruction>;
    productionRecord: Delegate<ProductionRecord>;
    qualityAudit: Delegate<QualityAudit>;
    qualityDefect: Delegate<QualityDefect>;
    packingList: Delegate<PackingList>;
    carton: Delegate<Carton>;
    shipment: Delegate<Shipment>;
    costingRecord: Delegate<CostingRecord>;
    costLine: Delegate<CostLine>;
    proformaInvoice: Delegate<ProformaInvoice>;
    proformaInvoiceLine: Delegate<ProformaInvoiceLine>;
    attachment: Delegate<Attachment>;
    activityLog: Delegate<ActivityLog>;
    auditTrail: Delegate<AuditTrail>;
    notification: Delegate<Notification>;
    changeEvent: Delegate<ChangeEvent>;
    changeEventField: Delegate<ChangeEventField>;
    emailDelivery: Delegate<EmailDelivery>;
    importJob: Delegate<ImportJob>;
    savedColumnMapping: Delegate<SavedColumnMapping>;
    $connect(): Promise<void>;
    $disconnect(): Promise<void>;
    $use(mw: Prisma.Middleware): void;
    $transaction<T>(fn: (tx: Prisma.TransactionClient) => Promise<T>, opts?: any): Promise<T>;
    $transaction<T>(ops: Promise<T>[]): Promise<T[]>;
    $queryRaw(q: TemplateStringsArray, ...v: any[]): Promise<any>;
    $executeRaw(q: TemplateStringsArray, ...v: any[]): Promise<number>;
  }
}
